basePath: /
definitions:
  model.RegionInfo:
    properties:
      active:
        type: string
      cured:
        type: string
      death:
        type: string
      new_active:
        type: string
      new_cured:
        type: string
      new_death:
        type: string
      new_positive:
        type: string
      positive:
        type: string
      region_code:
        type: string
      region_name:
        type: string
      rno:
        type: string
      updated_at:
        type: string
    type: object
  wrapper.Props:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Covid Stats for your region
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Covstats Swagger API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Props'
            - properties:
                Data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Check server status
      tags:
      - root
  /lat/{lat}/lon/{lon}:
    get:
      consumes:
      - application/json
      parameters:
      - description: latitude
        in: path
        name: lat
        required: true
        type: string
      - description: longitude
        in: path
        name: lon
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Props'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/model.RegionInfo'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Props'
            - properties:
                Data:
                  type: string
                Success:
                  type: boolean
                code:
                  type: integer
              type: object
      summary: Get state from lat, lon and send covstats in that state and India
      tags:
      - root
  /states:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Props'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/model.RegionInfo'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/wrapper.Props'
            - properties:
                Data:
                  type: string
                Success:
                  type: boolean
                code:
                  type: integer
              type: object
      summary: Get Covid Stats for all States in India from mohfw
      tags:
      - root
schemes:
- http
swagger: "2.0"
